server:
  port: ${PORT:0}
spring:
  application:
    name: stock-service
  datasource:
    username: root
    password: Root@123
    url: jdbc:mysql://localhost:3306/db_stock?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8001/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

